# Generated by Django 3.2.25 on 2025-11-17 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80)),
                ('matricula', models.CharField(max_length=30)),
                ('curso', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeExtracurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('situacao', models.CharField(max_length=50)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField()),
                ('situacao', models.BooleanField(default=False)),
                ('fk_aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='site_pfi.aluno')),
                ('fk_atividade_extracurricular', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='site_pfi.atividadeextracurricular')),
            ],
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('arquivo', models.ImageField(upload_to='')),
                ('extensao', models.CharField(max_length=10)),
                ('fk_atividade_extracurricular', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='site_pfi.atividadeextracurricular')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('formacao', models.CharField(max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(max_length=50)),
                ('fk_atividade_extracurricular', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='site_pfi.atividadeextracurricular')),
                ('fk_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_pfi.docente')),
            ],
        ),
        migrations.AddField(
            model_name='atividadeextracurricular',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='site_pfi.docente'),
        ),
        migrations.CreateModel(
            name='AlunoParticipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField(blank=True, null=True)),
                ('carga_horaria_semanal', models.IntegerField()),
                ('fk_aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='site_pfi.aluno')),
                ('fk_atividade_extracurricualar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='site_pfi.atividadeextracurricular')),
            ],
        ),
    ]
